# Dementia Project

Linear Regression
Logistic Regression
SVM
Neural Networks

In [2]:
# Run this code cell using Shift + Enter before moving further
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model, preprocessing
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline 

# Loading the data set.

In [3]:
# After completing the code in this code cell, run this code cell before moving further.

df = pd.read_csv('oasis_cross-sectional.csv',na_values='?') 
print(df.shape)
print(df)

(436, 12)
                ID M/F Hand  Age  Educ  SES  MMSE  CDR  eTIV   nWBV    ASF  \
0    OAS1_0001_MR1   F    R   74   2.0  3.0  29.0  0.0  1344  0.743  1.306   
1    OAS1_0002_MR1   F    R   55   4.0  1.0  29.0  0.0  1147  0.810  1.531   
2    OAS1_0003_MR1   F    R   73   4.0  3.0  27.0  0.5  1454  0.708  1.207   
3    OAS1_0004_MR1   M    R   28   NaN  NaN   NaN  NaN  1588  0.803  1.105   
4    OAS1_0005_MR1   M    R   18   NaN  NaN   NaN  NaN  1737  0.848  1.010   
..             ...  ..  ...  ...   ...  ...   ...  ...   ...    ...    ...   
431  OAS1_0285_MR2   M    R   20   NaN  NaN   NaN  NaN  1469  0.847  1.195   
432  OAS1_0353_MR2   M    R   22   NaN  NaN   NaN  NaN  1684  0.790  1.042   
433  OAS1_0368_MR2   M    R   22   NaN  NaN   NaN  NaN  1580  0.856  1.111   
434  OAS1_0379_MR2   F    R   20   NaN  NaN   NaN  NaN  1262  0.861  1.390   
435  OAS1_0395_MR2   F    R   26   NaN  NaN   NaN  NaN  1283  0.834  1.368   

     Delay  
0      NaN  
1      NaN  
2      NaN  
3

In [4]:
# ID M/F Hand  Age  Educ  SES  MMSE  CDR  eTIV   nWBV    ASF

df1= df[['M/F', 'Age', 'eTIV', 'nWBV', 'ASF', 'CDR']]
print(df1)

df2= df1.dropna()

print(df2)

    M/F  Age  eTIV   nWBV    ASF  CDR
0     F   74  1344  0.743  1.306  0.0
1     F   55  1147  0.810  1.531  0.0
2     F   73  1454  0.708  1.207  0.5
3     M   28  1588  0.803  1.105  NaN
4     M   18  1737  0.848  1.010  NaN
..   ..  ...   ...    ...    ...  ...
431   M   20  1469  0.847  1.195  NaN
432   M   22  1684  0.790  1.042  NaN
433   M   22  1580  0.856  1.111  NaN
434   F   20  1262  0.861  1.390  NaN
435   F   26  1283  0.834  1.368  NaN

[436 rows x 6 columns]
    M/F  Age  eTIV   nWBV    ASF  CDR
0     F   74  1344  0.743  1.306  0.0
1     F   55  1147  0.810  1.531  0.0
2     F   73  1454  0.708  1.207  0.5
8     M   74  1636  0.689  1.073  0.0
9     F   52  1321  0.827  1.329  0.0
..   ..  ...   ...    ...    ...  ...
411   F   70  1295  0.748  1.355  0.5
412   F   73  1536  0.730  1.142  0.5
413   F   61  1354  0.825  1.297  0.0
414   M   61  1637  0.780  1.072  0.0
415   F   62  1372  0.766  1.279  0.0

[235 rows x 6 columns]


In [40]:
x = np.array(df2[['M/F', 'Age', 'eTIV', 'nWBV', 'ASF']])
y = np.array(df2['CDR'])

y = y.reshape(-1,1)

for entry in x:
    if entry[0] == 'F':
        entry[0] = 0
    else:
        entry[0] = 1

for entry in y:
    if entry[0] != 0:
        entry[0] = 1
        
print(type(y[0][0]))

print(x.shape)
print(y.shape)

<class 'numpy.float64'>
(235, 5)
(235, 1)


In [45]:
# Converting our y values into ints

lab_enc = preprocessing.LabelEncoder()
y = lab_enc.fit_transform(y)

print(y[0])

0


In [46]:
#Scaling & Splitting Data
x = preprocessing.scale(x)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.275)
print(x)
print(x_train.shape)
print(y_test.shape)

[[-0.71162508  0.1371931  -0.72174218 -0.12827252  0.6929025 ]
 [-0.71162508 -1.43752977 -1.95278831  1.27328952  2.43504324]
 [-0.71162508  0.05431295 -0.03435601 -0.8604318  -0.07363942]
 ...
 [-0.71162508 -0.94024886 -0.65925253  1.58707206  0.62321687]
 [ 1.40523434 -0.94024886  1.10920461  0.64572442 -1.11892387]
 [-0.71162508 -0.85736871 -0.54677115  0.35286071  0.48384561]]
(170, 5)
(65,)


In [47]:
# Linear Regression (SIMPLE)

reg = LinearRegression().fit(x_train, y_train)
rsq = reg.score(x_train, y_train)
coef = reg.coef_
intercept = reg.intercept_

print(rsq)

0.26243119892196454


In [48]:
yhat = reg.predict(x_test)
#print(yhat)

##CONTINUE...

In [73]:
#LOGISTIC REGRESSION - w L2 Regularization
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_fscore_support

acc_train_logreg = []
acc_test_logreg = []
c_logreg = [0.001, 0.01, 0.1, 1, 10, 100, 1000]
logreg_objs = []

# TODO - Create object of logistic regression model. Pass a large value of C (C = 1/lambda) to make lambda nearly 0. - 5 points
for c in c_logreg:
    print('cVal:', c)
    logreg = LogisticRegression(C=c, solver='lbfgs')
    logreg.fit(x_train, y_train)
    logreg_objs.append(logreg)
    
    yhat_tr =  logreg.predict(x_train)
    acc_train = logreg.score(x_train, y_train)

    acc_train_logreg.append(acc_train)
    print("Accuracy on training data = %f" % acc_train)

    yhat_test = logreg.predict(x_test)
    acc_test = logreg.score(x_test, y_test)

    acc_test_logreg.append(acc_test)
    print("Accuracy on testing data = %f" % acc_test)
    print()

cVal: 0.001
Accuracy on training data = 0.576471
Accuracy on testing data = 0.569231

cVal: 0.01
Accuracy on training data = 0.658824
Accuracy on testing data = 0.615385

cVal: 0.1
Accuracy on training data = 0.711765
Accuracy on testing data = 0.692308

cVal: 1
Accuracy on training data = 0.705882
Accuracy on testing data = 0.692308

cVal: 10
Accuracy on training data = 0.711765
Accuracy on testing data = 0.676923

cVal: 100
Accuracy on training data = 0.711765
Accuracy on testing data = 0.676923

cVal: 1000
Accuracy on training data = 0.711765
Accuracy on testing data = 0.676923



In [72]:
best_test_acc = max(acc_test_logreg)
i = acc_test_logreg.index(best_test_acc)
print('Accuracy on training data:', acc_train_logreg[i])
print('Accuracy on testing data:', acc_test_logreg[i])

logreg = logreg_objs[i]

w = logreg.coef_ 
intercept = logreg.intercept_

print('w:', w)
print('intercept:', intercept)

prec , recal , fscore,_ = precision_recall_fscore_support(y_test, yhat_test)
print('prec:', prec)
print('recall:', recal)
print('fscore:', fscore)


Accuracy on training data: 0.711764705882353
Accuracy on testing data: 0.6923076923076923
w: [[ 0.14402674  0.21098956  0.05924867 -0.75158871 -0.04509271]]
intercept: [-0.38816163]
prec: [0.69047619 0.65217391]
recall: [0.78378378 0.53571429]
fscore: [0.73417722 0.58823529]


In [74]:
# SVM 

In [ ]:
from sklearn import svm